name: Build Cordova Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout
      - uses: actions/checkout@v4

      # 2Ô∏è‚É£ Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3Ô∏è‚É£ Java 17
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 4Ô∏è‚É£ Android SDK
      - uses: android-actions/setup-android@v3
        with:
          api-level: 32
          build-tools: 32.0.0

      # 5Ô∏è‚É£ Install Cordova
      - run: npm install -g cordova@12

      # 6Ô∏è‚É£ Dependencies
      - run: npm install

           # 7Ô∏è‚É£ Android Platform (STABLE)
      - run: |
          cordova platform rm android || true
          cordova platform add android@11.0.0

      # 8Ô∏è‚É£ Prepare Android (REQUIRED)
      - name: Prepare Android
        run: cordova prepare android

     


      # 8Ô∏è‚É£ Firebase config
      - run: |
          mkdir -p platforms/android/app
          echo "$GOOGLE_SERVICES_JSON" > platforms/android/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      # 9Ô∏è‚É£ Build APK
      - run: cordova build android --debug --no-interactive

      # üîü Upload
      - uses: actions/upload-artifact@v4
        with:
          name: Homey-Vendor-APK
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
